language: scala

jdk:
  - oraclejdk8
scala:
  - 2.12.1
env:
  secure: "xlQujF44XB76fpRNG4oDkVNsWtsDcs4VQAaH7I1CMSHJCscUguls8BSWFxz5ikUliRqmQ1RfjJRRPI9VmQWPKjfVrqwLn4WcWXUU9rb1pC0hHhxflWR+7fDvu3SaLcyegeVHjD1DiBuCjoWXs0U/eIfce2Bvvlvf3y6sLmDIVX5dY+nIhdaHl/uw/8bL/CJzj1SN9BEahodvz2dWx/JPVTCx3iyBR+TIvPdbLTxbhAni+SxJehO2ub5Mh5cIO+K7O2fsMrZMV1H1AvKedF05izpjiKQdaL7Tt8iOdmobjpK4vp/Qvfw6tSb9Jgmn1f3qFJic2jQvsGnJSRzufIHSVOUCcbSiPqXJwzsJob70i6RliEUTweywBGsDD+rlM52Mo0mrVkD5D/VLyyzTutMgEkeiqPx4ReY2EvDu0/QG3tKiZZT76zFcqZdYGQj8OOHE1azenf+RmLrOpBn4D74PcRw8TLGU0+M9yKfL3YHvTa0ae1y84EkUWHLXZ3ZDXMLh8DLt3XKDQKyOf+KFM764OmotPJKSoISYl1YNt0Qk9GFXkCYpUxK4QYcmndw3vFcCUBtyWTvl0I2T14Jqgodm5BQYyXG8FhSvLrA4gHgHF28qA3e6JSk49Y9Mz99iyGYzH0mQJdFAIHgbK7ZNm00N9HXU7leaReXJKvuIu6MOAnc="
after_success:
  - ./gradlew jacocoTestReport coveralls